# Generated by Django 2.2 on 2020-09-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics',
            new_name='Boards',
        ),
    ]
