# Generated by Django 2.2 on 2020-09-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_post_fils'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_fils',
            new_name='Post_files',
        ),
    ]
