# Generated by Django 2.2 on 2020-09-13 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20200913_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_files',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_files', to='forum.Posts'),
        ),
    ]
