# Generated by Django 2.2 on 2020-09-15 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20200915_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='created_at',
            field=models.DateTimeField(default='2020-09-15 05:32:10'),
        ),
        migrations.AlterField(
            model_name='post_files',
            name='created_at',
            field=models.DateTimeField(default='2020-09-15 05:32:10'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default='2020-09-15 05:32:10'),
        ),
        migrations.AlterField(
            model_name='recommands',
            name='created_at',
            field=models.DateTimeField(default='2020-09-15 05:32:10'),
        ),
        migrations.CreateModel(
            name='recommand_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default='2020-09-15 05:32:10')),
                ('updated_at', models.DateTimeField(null=True)),
                ('recommand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommand_files', to='forum.Posts')),
            ],
        ),
    ]
