# Generated by Django 2.2 on 2020-09-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_auto_20200918_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='created_at',
            field=models.DateTimeField(default='2020-09-18 07:11:38'),
        ),
        migrations.AlterField(
            model_name='post_files',
            name='created_at',
            field=models.DateTimeField(default='2020-09-18 07:11:38'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default='2020-09-18 07:11:38'),
        ),
        migrations.AlterField(
            model_name='recommand_files',
            name='created_at',
            field=models.DateTimeField(default='2020-09-18 07:11:38'),
        ),
        migrations.AlterField(
            model_name='recommands',
            name='created_at',
            field=models.DateTimeField(default='2020-09-18 07:11:38'),
        ),
    ]
