# Generated by Django 2.2 on 2020-09-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0025_auto_20200918_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='other',
            field=models.CharField(default='stuff', max_length=100),
        ),
        migrations.AddField(
            model_name='posts',
            name='pref',
            field=models.CharField(default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='boards',
            name='created_at',
            field=models.DateTimeField(default='2020-09-22 10:49:20'),
        ),
        migrations.AlterField(
            model_name='post_files',
            name='created_at',
            field=models.DateTimeField(default='2020-09-22 10:49:20'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default='2020-09-22 10:49:20'),
        ),
        migrations.AlterField(
            model_name='recommand_files',
            name='created_at',
            field=models.DateTimeField(default='2020-09-22 10:49:20'),
        ),
        migrations.AlterField(
            model_name='recommands',
            name='created_at',
            field=models.DateTimeField(default='2020-09-22 10:49:20'),
        ),
    ]
