# Generated by Django 2.2 on 2020-09-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0026_auto_20200922_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='boards',
            name='created_at',
            field=models.DateTimeField(default='2020-09-23 10:19:37'),
        ),
        migrations.AlterField(
            model_name='post_files',
            name='created_at',
            field=models.DateTimeField(default='2020-09-23 10:19:37'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default='2020-09-23 10:19:37'),
        ),
        migrations.AlterField(
            model_name='recommand_files',
            name='created_at',
            field=models.DateTimeField(default='2020-09-23 10:19:37'),
        ),
        migrations.AlterField(
            model_name='recommands',
            name='created_at',
            field=models.DateTimeField(default='2020-09-23 10:19:37'),
        ),
    ]
