# Generated by Django 2.2 on 2020-09-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0028_auto_20200923_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='created_at',
            field=models.DateTimeField(default='2020-09-23 10:27:11'),
        ),
        migrations.AlterField(
            model_name='post_files',
            name='created_at',
            field=models.DateTimeField(default='2020-09-23 10:27:11'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default='2020-09-23 10:27:11'),
        ),
        migrations.AlterField(
            model_name='recommand_files',
            name='created_at',
            field=models.DateTimeField(default='2020-09-23 10:27:11'),
        ),
        migrations.AlterField(
            model_name='recommands',
            name='created_at',
            field=models.DateTimeField(default='2020-09-23 10:27:11'),
        ),
    ]
