# Generated by Django 2.2 on 2020-09-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0031_auto_20200923_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='created_at',
            field=models.DateTimeField(default='2020-09-24 09:35:02'),
        ),
        migrations.AlterField(
            model_name='post_files',
            name='created_at',
            field=models.DateTimeField(default='2020-09-24 09:35:02'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default='2020-09-24 09:35:02'),
        ),
        migrations.AlterField(
            model_name='recommand_files',
            name='created_at',
            field=models.DateTimeField(default='2020-09-24 09:35:02'),
        ),
        migrations.AlterField(
            model_name='recommands',
            name='created_at',
            field=models.DateTimeField(default='2020-09-24 09:35:02'),
        ),
    ]
