# Generated by Django 2.2 on 2021-02-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelme_ncku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='npy_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
