# Generated by Django 2.2 on 2021-02-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelme_ncku', '0004_auto_20210222_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='dictionary_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
