# Generated by Django 2.2 on 2021-05-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelme_ncku', '0006_auto_20210308_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='input_imgs',
            name='patient_folder_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
