# Generated by Django 2.2 on 2020-11-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201105_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='isadmin',
            new_name='is_admin',
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default='2020-11-09 16:35:21'),
        ),
    ]
