# Generated by Django 2.2 on 2020-12-02 16:06

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0014_auto_20201202_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='date_joined',
            field=models.DateTimeField(default='2020-12-02 16:06:28'),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='is_staff',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='is_superuser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(default='2020-12-02 16:06:28'),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default='2020-12-02 16:06:28'),
        )
    ]
