# Generated by Django 2.2 on 2020-10-22 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20201022_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='option_users',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_users', to='exams.Exams'),
        ),
    ]
