# Generated by Django 2.2 on 2020-10-28 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_option_users_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_users',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_users', to='accounts.Users'),
        ),
        migrations.CreateModel(
            name='Exam_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_files', to='exams.Exams')),
            ],
        ),
    ]
