# Generated by Django 2.2 on 2020-10-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20201028_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_files',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
