# Generated by Django 2.2 on 2020-10-30 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_files_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_files',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_files', to='exams.Questions'),
        ),
    ]
