# Generated by Django 2.2 on 2020-11-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exam_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='option_users',
            name='user_exam_count',
            field=models.IntegerField(default=1),
        ),
    ]
