# Generated by Django 2.2 on 2020-11-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_option_users_user_exam_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option_users',
            name='user_exam_count',
        ),
        migrations.AddField(
            model_name='exam_users',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option_users',
            name='exam_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_users', to='exams.Exam_Users'),
        ),
    ]
