# Generated by Django 2.2 on 2020-11-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20201111_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_users',
            name='status',
        ),
        migrations.AddField(
            model_name='exam_users',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
