# Generated by Django 2.2 on 2020-11-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_auto_20201112_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='next_question_id',
            field=models.IntegerField(null=True),
        ),
    ]
